version: "3.7"
volumes:
    postgres-data:
    redis-data:
    geoserver-data:
networks:
    frontend:
    backend:
services:
    proxy:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/nginx-site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - frontend
            - backend
    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        image: laravelgis-php:latest
        ports:
            - "5173:5173"
        volumes:
            - ./:/var/www/app
        networks:
            - backend
    postgres:
        image: postgis/postgis:15-3.3
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: 12345
            POSTGRES_USER: laravelgis
            POSTGRES_DB: laravelgis
            PGDATA: /var/lib/postgresql/data
        networks:
            - backend
    redis:
        image: redis:7
        sysctls:
            - net.core.somaxconn=511
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        networks:
            - backend
    geoserver:
        image: kartoza/geoserver:2.22.0
        volumes:
            - geoserver-data:/opt/geoserver/data_dir
        environment:
            - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
            - GEOSERVER_ADMIN_USER=admin
            - GEOSERVER_ADMIN_PASSWORD=geoserver
        networks:
            - backend